"""empty message

Revision ID: 1c78763c153b
Revises: ed40b100ed7e
Create Date: 2021-12-27 17:31:14.556328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c78763c153b'
down_revision = 'ed40b100ed7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('create_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'create_date')
    # ### end Alembic commands ###
