"""empty message

Revision ID: 44e158e02a84
Revises: b6b89e792ff9
Create Date: 2021-12-17 18:26:32.967708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44e158e02a84'
down_revision = 'b6b89e792ff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_game', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('site_link', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('steam', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('twitter', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('instagram', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('facebook', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('users', sa.Column('last_session', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_session')
    op.drop_column('users', 'about_me')
    op.drop_column('users', 'facebook')
    op.drop_column('users', 'instagram')
    op.drop_column('users', 'twitter')
    op.drop_column('users', 'steam')
    op.drop_column('users', 'site_link')
    op.drop_column('users', 'favorite_game')
    # ### end Alembic commands ###
